name: Publish LLMterface to PyPI

on:
  push:
    tags:
      - "llmterface-v*"


jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Verify tag matches pyproject version
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#llmterface-v}"

          PYPROJECT_VERSION=$(python - <<'PY'
          import tomllib, pathlib
          data = tomllib.loads(
              pathlib.Path("packages/llmterface/pyproject.toml").read_text()
          )
          print(data["project"]["version"])
          PY
          )

          echo "Tag version:        $TAG_VERSION"
          echo "pyproject version:  $PYPROJECT_VERSION"

          if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
            echo "ERROR: Tag version does not match pyproject.toml version"
            exit 1
          fi

      - name: Build
        working-directory: packages/llmterface
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m build

      - name: Verify dist artifacts exist
        run: |
          set -euo pipefail
          shopt -s nullglob

          DIST_DIR="packages/llmterface/dist"
          wheels=("$DIST_DIR"/*.whl)
          sdists=("$DIST_DIR"/*.tar.gz)

          if (( ${#wheels[@]} == 0 )); then
            echo "ERROR: No .whl found in $DIST_DIR"
            ls -la "$DIST_DIR" || true
            exit 1
          fi

          if (( ${#sdists[@]} == 0 )); then
            echo "ERROR: No .tar.gz sdist found in $DIST_DIR"
            ls -la "$DIST_DIR" || true
            exit 1
          fi

          echo "Found wheel(s): ${wheels[*]}"
          echo "Found sdist(s): ${sdists[*]}"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/llmterface/dist/
